# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Festival-App' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  inhibit_all_warnings!

  # Pods for Festival-App
  pod 'Alamofire'
  pod 'SwiftyJSON'
  pod 'Socket.IO-Client-Swift'
  pod 'AWSCore'
  pod 'AWSCognito'
  pod 'AWSS3'
  pod 'NVActivityIndicatorView'
  pod 'lottie-ios'
  pod 'Firebase/Database'
  pod 'Firebase/Auth'
  pod 'Firebase/Core'

  target 'Festival-AppTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
